# Copyright 2026 The JAX Authors.

"""Jax C++ jit library type stub."""

from collections.abc import Sequence
import numpy
from jax._src.lib.pytree import PyTreeDef, PyTreeRegistry

class PyArgSignature:
  @property
  def dtype(self) -> numpy.dtype[Any]: ...
  @property
  def shape(self) -> tuple[int, ...]: ...
  @property
  def weak_type(self) -> bool: ...

class ArgumentSignature:
  @property
  def static_args(self) -> list[object]: ...
  @property
  def static_arg_names(self) -> list[str]: ...
  @property
  def dynamic_arg_names(self) -> list[str]: ...
  @property
  def dynamic_arg_treedefs(self) -> Sequence[PyTreeDef]: ...
  def __repr__(self) -> str: ...
  def __str__(self) -> str: ...
  def __hash__(self) -> int: ...
  def __eq__(self, arg: object, /) -> bool: ...

def parse_arguments(
    positional_args: Sequence[object],
    keyword_args: Sequence[object],
    kwnames: tuple[str, ...],
    static_argnums: Sequence[int],
    static_argnames: Sequence[str],
    pytree_registry: PyTreeRegistry,
) -> tuple[ArgumentSignature, list[object]]: ...
